import { Geist, Geist_Mono, Rubik_Gemstones } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rubik = Rubik_Gemstones({
  subsets: ["latin"],
  weight: ["400"],
});

const sigmar = localFont({
  src: "../../public/fonts/Sigmar-Regular.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sigmar.className}`}>
        <div className="bg-blue-500 text-white p-20 text-5xl">{children}</div>
      </body>
    </html>
  );
}
